import type { Metadata } from "next";
import "@/app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LandingPageLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    className="antialiased h-screen w-screen"
                >
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
